# Spring properties
spring:
  application:
     name: service2

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9090/eureka/

# HTTP Server
server:
  port: 9092   # HTTP (Tomcat) port
  servlet:
    context-path: /test
  